[package]
name = "subgraph"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-graphql = "7.0.6"
async-graphql-axum = "7.0.6"
axum = "0.7.5"
serde_json = "1.0.120"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
