[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.7.5"
serde_json = "1.0.120"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
